### ISSUE TITLE
Fix links in demo schedule

### ISSUE THREAD

**Issue by ugurdogrusoz** [emredikenelli/1C.Wheres-My-Ring#8]
https://docs.google.com/spreadsheets/d/1zyqpM1mWtpX23uFWd7U0AiET1ahgoEykSmflEGwHvVI/edit#gid=1906157894

**Comment by ghost** [comment]
I have fixed the link in the schedule.

**Comment by ghost** [comment]
Sir, the links have been fixed. You can check the links and close this issue. 
Thank you.
